### ISSUE TITLE
angular-katex auto-render show error ParseError: KaTeX parse error: Unexpected 

### ISSUE THREAD

**Issue by leoluu** [tfoxy/angular-katex#1]
![image](https://cloud.githubusercontent.com/assets/5054131/9677146/f6d71746-5308-11e5-855b-71fe12956e0a.png)
how to make angular-katex auto-render,it show error ParseError: KaTeX parse error: Unexpected character: '$' at position 0: ̲$When a \ne 0$

**Comment by tfoxy** [comment]
The ''$' characters are not necessary. Everything you type in the input will be in math mode.

![ng-katex-1](https://cloud.githubusercontent.com/assets/6027291/9687197/75c748d8-52fe-11e5-957f-ceb76e403145.png)

I suppose you want "When" to appear as text. You can use the `\text` command:

![ng-katex-2](https://cloud.githubusercontent.com/assets/6027291/9687272/dd239306-52fe-11e5-828d-d0bad2d81217.png)

Let me know if this fixes your problem.

**Comment by leoluu** [comment]
aha,you are very kind @tfoxy .
when i print "When a \ne 0, there are two solutions to (ax^2 + bx + c = 0) and they are x = {-b \pm \sqrt{b^2-4ac} \over 2a}." in live demo,it show
![image](https://cloud.githubusercontent.com/assets/5054131/9696827/1a07e0a4-53ab-11e5-9586-08d1e049ce5b.png)
show word without blank.
i add $ delimiter expect angular-katex just compile the math expression between $ show like this
![aa](https://cloud.githubusercontent.com/assets/5054131/9697029/19ca3ae2-53b0-11e5-829d-2dbd018d3303.png)

i also want this work well in chinese.
i print  数学公式：\left(\sum_{i=1}^{k}i\right) +(k+1)
![image](https://cloud.githubusercontent.com/assets/5054131/9697482/c58750f2-53c1-11e5-9fcd-2a2cd0d4f8d2.png)

and want it show like this 
![image](https://cloud.githubusercontent.com/assets/5054131/9697034/59525564-53b0-11e5-8f6f-bf3c6a4d67fd.png)

could give me a live demo or some help please.Thinks.

i have try your suggest and it didn't work
![image](https://cloud.githubusercontent.com/assets/5054131/9697049/c747327e-53b0-11e5-87ad-27c1adce086c.png)

**Comment by tfoxy** [comment]
I think I understand what you want.
You want to use the [auto-render extension](https://github.com/Khan/KaTeX/tree/master/contrib/auto-render).

In the following demo, I added the katex-auto-render directive:

[Live Demo](http://jsbin.com/valeka/5/embed?html,output)

Does this behaves as you expected? If it does, I will push the changes and release a new version.

**Comment by leoluu** [comment]
Aha…very very perfect, it is just what i want.
Waiting for you pull it soon.

**Comment by tfoxy** [comment]
I just uploaded version 0.8.0

To use the auto-render function, you need to include the `auto-render.min.js` file from katex. If you use bower, it is inside the `dist/contrib` folder. If not, you can download it from the [katex releases](https://github.com/Khan/KaTeX/releases).

By default, this extension does not use `$` as a delimiter. The default options are in the [README](https://github.com/Khan/KaTeX/tree/master/contrib/auto-render#api).
But you can add the `$` delimiter in the config phase of angular:

``` js
angular.module('app', ['katex'])
  .config(function(katexConfigProvider) {
    katexConfigProvider.defaultOptions.delimiters = [{left: "$", right: "$", display: false}];
  });
```

Finally, in the html, you need to add the `katex-auto-render` attribute.

``` js
<div katex-bind="equation" katex-auto-render></div>
```

I hope these instructions are clear.

EDIT: I added a little fix in v0.8.1

**Comment by leoluu** [comment]
yes, it is work smoothly after your help,thanks again.

**Comment by tfoxy** [comment]
Great! I'm glad it worked. I'm closing this issue.
