### ISSUE TITLE
how to make angular-katex  html encode

### ISSUE THREAD

**Issue by leoluu** [tfoxy/angular-katex#2]
Hi @tfoxy ,i want to impliment like this :
http://www.intmath.com/exponential-logarithmic-functions/3-logarithm-laws.php

![a](https://cloud.githubusercontent.com/assets/5054131/11164645/51a3021a-8b31-11e5-9165-6bf6de4b78f8.jpg)

in angular-katex :
http://jsbin.com/valeka/5/embed?html,output

![aa](https://cloud.githubusercontent.com/assets/5054131/11164647/5e0f1e9e-8b31-11e5-80b4-e9be69ab80d9.png)

it show without new line? could u help me?

**Comment by tfoxy** [comment]
Hi! That was something I removed because I was having trouble maintaining it. I will rewrite the code to make it cleaner and add this. Meanwhile, here is working example of what you want:

http://jsbin.com/valeka/8/embed?html,output

**Comment by tfoxy** [comment]
Hi @leoluu . Sorry for the long delay. v0.9.0 was released yesterday. You can use `<katex bind="tex" auto-render></katex>` to do what you want. Check the following example.

http://jsbin.com/valeka/9/embed?html,output
