### ISSUE TITLE
Anyway to set self-defined left and right delimiters for katex formulation?

### ISSUE THREAD

**Issue by dyzpku** [tfoxy/angular-katex#5]
Although in the end of readme.md, it suggests the property of  defaultOptions of katexConfigProvider can manipulate something related, I tried but failed.  What I did is based on the live example on JS Bin as follows:

```
angular.module('app', ['katex'])
    .config('katexConfig', katexConfig);

katexConfig.$inject = ['katexConfigProvider'];

function katexConfig(katexConfigProvider) {
  katexConfigProvider.defaultOptions = {delimiters : [{left: '#!@#$', right: '#$#!@', display: false}]};
};
```

As is stated above, I try to pass the option object which is defined according to [auto render options](https://github.com/Khan/KaTeX/blob/master/contrib/auto-render/README.md#api) to katexConfigProvider.defaultOptions. On this basis, I hope the formulations can be identified by self-defined delimiters in the way of  #!@#$formulation#$#!@. However, it is not recognized. Therefore I don't know if there is any way to achieve this target provided by angular-katex. Otherwise I can only use the native katex on which I can successfully do this. Looking forward to hear from you! Thanks!

**Comment by tfoxy** [comment]
The config recipe only receives one argument: a function. Try with the following code:

``` js
angular.module('app', ['katex'])
    .config(katexConfig);

katexConfig.$inject = ['katexConfigProvider'];

function katexConfig(katexConfigProvider) {
  katexConfigProvider.defaultOptions = {delimiters : [{left: '#!@#$', right: '#$#!@', display: false}]};
};
```

Here is a working example: http://jsbin.com/fekaleg/2/embed?html,js,output
